2 flaky-test.yml

diff --git a/.github/workflows/flaky-test.yml b/.github/workflows/flaky-test.yml
--- a/.github/workflows/flaky-test.yml
+++ b/.github/workflows/flaky-test.yml
@@ -3,58 +3,113 @@ name: Test Flaky Test
 on:
   push:
     branches:
-      - main  
+      - main
+  pull_request:
+    branches:
+      - main
 
 jobs:
-  test:
+  build-and-test:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout Code
-        uses: actions/checkout@v2
-        # with:
-        #   repository: apache/hive
-        #   ref: 90fa9064f2c6907fbe6237cb46d5937eebd8ea31
+    - name: Checkout repository
+      uses: actions/checkout@v3
 
-      - name: Set up JDK
-        uses: actions/setup-java@v2
-        with:
-          java-version: '8'  
-          distribution: 'adopt'
+    - name: Set up JDK 11
+      uses: actions/setup-java@v3
+      with:
+        distribution: 'adopt'
+        java-version: '11'
 
-      - name: Clone the typescript-generator repository
-        run: git clone https://github.com/vojtechhabarta/typescript-generator
-        working-directory: ${{ github.workspace }}
+    - name: Cache Maven packages
+      uses: actions/cache@v3
+      with:
+        path: ~/.m2/repository
+        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
+        restore-keys: |
+          ${{ runner.os }}-maven-
+
+    - name: Clone the typescript-generator repository
+      run: git clone https://github.com/vojtechhabarta/typescript-generator
+      working-directory: ${{ github.workspace }}
+
+    - name: Compile the module and dependencies
+      run: mvn test-compile -pl typescript-generator-core -am
+      working-directory: ${{ github.workspace }}/typescript-generator
+
+    - name: Run the test
+      run: mvn -pl typescript-generator-core test -Dtest=cz.habarta.typescript.generator.TaggedUnionsTest#testTaggedUnionsWithInterfaces
+      working-directory: ${{ github.workspace }}/typescript-generator
+
+    - name: Run NonDex tool to report flaky tests
+      id: nondex
+      run: |
+        mvn -pl typescript-generator-core edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=cz.habarta.typescript.generator.TaggedUnionsTest#testTaggedUnionsWithInterfaces || echo "NonDex failed" > nondex_result.txt
+      working-directory: ${{ github.workspace }}/typescript-generator
+      continue-on-error: true
+
+    - name: Check NonDex results
+      if: failure()
+      run: echo "has flaky"
+
+# name: Test Flaky Test
+
+# on:
+#   push:
+#     branches:
+#       - main  
+
+# jobs:
+#   test:
+#     runs-on: ubuntu-latest
+
+#     steps:
+#       - name: Checkout Code
+#         uses: actions/checkout@v2
+#         # with:
+#         #   repository: apache/hive
+#         #   ref: 90fa9064f2c6907fbe6237cb46d5937eebd8ea31
+
+#       - name: Set up JDK
+#         uses: actions/setup-java@v2
+#         with:
+#           java-version: '8'  
+#           distribution: 'adopt'
+
+#       - name: Clone the typescript-generator repository
+#         run: git clone https://github.com/vojtechhabarta/typescript-generator
+#         working-directory: ${{ github.workspace }}
   
-      - name: Compile the module and dependencies
-        run: mvn test-compile -pl typescript-generator-core -am
-        working-directory: ${{ github.workspace }}/typescript-generator
+#       - name: Compile the module and dependencies
+#         run: mvn test-compile -pl typescript-generator-core -am
+#         working-directory: ${{ github.workspace }}/typescript-generator
   
-      - name: Run the test
-        run: mvn -pl typescript-generator-core test -Dtest=cz.habarta.typescript.generator.JsonDeserializationTest#testWithConstructors
-        working-directory: ${{ github.workspace }}/typescript-generator
+#       - name: Run the test
+#         run: mvn -pl typescript-generator-core test -Dtest=cz.habarta.typescript.generator.JsonDeserializationTest#testWithConstructors
+#         working-directory: ${{ github.workspace }}/typescript-generator
   
-      - name: Run NonDex tool to report flaky tests
-        id: nondex
-        run: |
-          mvn -pl typescript-generator-core edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=cz.habarta.typescript.generator.JsonDeserializationTest#testWithConstructors || echo "NonDex failed" > nondex_result.txt
-        working-directory: ${{ github.workspace }}/typescript-generator
-        continue-on-error: true
+#       - name: Run NonDex tool to report flaky tests
+#         id: nondex
+#         run: |
+#           mvn -pl typescript-generator-core edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=cz.habarta.typescript.generator.JsonDeserializationTest#testWithConstructors || echo "NonDex failed" > nondex_result.txt
+#         working-directory: ${{ github.workspace }}/typescript-generator
+#         continue-on-error: true
   
-      - name: Check NonDex results
-        if: failure()
-        run: echo "has flaky"
+#       - name: Check NonDex results
+#         if: failure()
+#         run: echo "has flaky"
       
-      # - name: Compile and Test
-      #   run: |
-      #     mvn test-compile -pl standalone-metastore/metastore-server/pom.xml -am
-      #     mvn test -pl standalone-metastore/metastore-server/pom.xml -Dtest=org.apache.hadoop.hive.metastore.TestPartitionManagement#testPartitionDiscoveryNonDefaultCatalog
-      # - name: Get nondexTests
-      #   run: nondexTests=$(git diff --name-status --diff-filter=AM ${{ github.event.before }} ${{ github.sha }} | grep /test/ | sed -e 's;.*test/java/;;' -e 's/.java//' -e 's;/;.;g' | tr '\n' ','); echo $nondexTests;
-      # - name: Run NonDex
-      #   run: if [ ! -z $nondexTests ]; then printf "Running NonDex on tests:\n$nondexTests \n" ; mvn -B edu.illinois:nondex-maven-plugin:1.1.2:nondex  -DnondexRuns=10 -DfailIfNoTests=false -Dtest=$nondexTests ; fi
-      # - name: Find flakyTests 
-      #   run: if [ -d ".nondex" ]; then flakyTests=$(awk ' !x[$0]++' .nondex/*/failures); fi
-      # - name: Output flakyTests
-      #   run: if [ ! -z "$flakyTests" ]; then printf "Found flaky tests:\n$flakyTests \n" ; exit 1 ; else printf "No flaky tests found.\n" ; fi
+#       # - name: Compile and Test
+#       #   run: |
+#       #     mvn test-compile -pl standalone-metastore/metastore-server/pom.xml -am
+#       #     mvn test -pl standalone-metastore/metastore-server/pom.xml -Dtest=org.apache.hadoop.hive.metastore.TestPartitionManagement#testPartitionDiscoveryNonDefaultCatalog
+#       # - name: Get nondexTests
+#       #   run: nondexTests=$(git diff --name-status --diff-filter=AM ${{ github.event.before }} ${{ github.sha }} | grep /test/ | sed -e 's;.*test/java/;;' -e 's/.java//' -e 's;/;.;g' | tr '\n' ','); echo $nondexTests;
+#       # - name: Run NonDex
+#       #   run: if [ ! -z $nondexTests ]; then printf "Running NonDex on tests:\n$nondexTests \n" ; mvn -B edu.illinois:nondex-maven-plugin:1.1.2:nondex  -DnondexRuns=10 -DfailIfNoTests=false -Dtest=$nondexTests ; fi
+#       # - name: Find flakyTests 
+#       #   run: if [ -d ".nondex" ]; then flakyTests=$(awk ' !x[$0]++' .nondex/*/failures); fi
+#       # - name: Output flakyTests
+#       #   run: if [ ! -z "$flakyTests" ]; then printf "Found flaky tests:\n$flakyTests \n" ; exit 1 ; else printf "No flaky tests found.\n" ; fi
     
