Update flaky-test.yml

diff --git a/.github/workflows/flaky-test.yml b/.github/workflows/flaky-test.yml
--- a/.github/workflows/flaky-test.yml
+++ b/.github/workflows/flaky-test.yml
@@ -34,7 +34,7 @@ jobs:
           java-version: '8'
       - name: Run NonDex tool to report flaky tests
         id: nondex
-        run: mvn -pl mockserver-core edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=org.mockserver.serialization.serializers.body.JsonBodySerializerTest#shouldSerializeJsonBodyAsObject -DnondexRuns=10  || echo "NonDex failed" > nondex_result.txt
+        run: mvn -pl mockserver-core edu.illinois:nondex-maven-plugin:1.1.2:debug -Dtest=org.mockserver.serialization.serializers.body.JsonBodySerializerTest#shouldSerializeJsonBodyAsObject -DnondexRuns=10  || echo "NonDex failed" > nondex_result.txt
         working-directory: ${{ github.workspace }}/mockserver
         continue-on-error: true
       - name: Check NonDex results
