Update flaky-test.yml

diff --git a/.github/workflows/flaky-test.yml b/.github/workflows/flaky-test.yml
--- a/.github/workflows/flaky-test.yml
+++ b/.github/workflows/flaky-test.yml
@@ -1,43 +1,60 @@
-name: Test Flaky Test
+name: Test Flaky
+
 on:
-  push:
-    branches:
-      - main
-  pull_request:
-    branches:
-      - main
+  push: {}
+
 jobs:
   build-and-test:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@v3
-      - name: Set up JDK 11
-        uses: actions/setup-java@v2
+      - uses: actions/checkout@v3
+      - name: Set up Java environment
+        uses: actions/setup-java@v3
         with:
-          distribution: 'adopt'
-          java-version: '17'
-      - name: Clone the typescript-generator repository
-        run: git clone https://github.com/zalando/riptide
-        working-directory: ${{ github.workspace }}
-      - name: Compile the module and dependencies (with tests)
-        run: mvn package -DskipTests  
-        working-directory: ${{ github.workspace }}/riptide
+          java-version: 11
+      - name: Install dependencies
+        run: mvn install
+      - name: Run tests
+        run: mvn test
+      - name: Run NonDex tests for AnchorTest
+        run: mvn -pl schemacrawler-utility edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=us.fatehi.utility.test.html.AnchorTest#anchor2 -DnondexRuns=10
+#     branches:
+#       - main
+#   pull_request:
+#     branches:
+#       - main
+# jobs:
+#   build-and-test:
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Checkout repository
+#         uses: actions/checkout@v3
+#       - name: Set up JDK 11
+#         uses: actions/setup-java@v2
+#         with:
+#           distribution: 'adopt'
+#           java-version: '17'
+#       - name: Clone the typescript-generator repository
+#         run: git clone https://github.com/zalando/riptide
+#         working-directory: ${{ github.workspace }}
+#       - name: Compile the module and dependencies (with tests)
+#         run: mvn package -DskipTests  
+#         working-directory: ${{ github.workspace }}/riptide
 
-      # - name: Run the test
-      #   run: mvn -pl mockserver-core test -Dtest=org.mockserver.serialization.serializers.body.JsonBodySerializerTest#shouldSerializeJsonBodyAsObject
-      #   working-directory: ${{ github.workspace }}/mockserver
-      - name: Set up JDK 8 for NonDex
-        uses: actions/setup-java@v2
-        with:
-          distribution: 'adopt'
-          java-version: '8'
-      - name: Run NonDex tool to report flaky tests
-        id: nondex
-        run: mvn -pl riptide-spring-boot-starter edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=org.zalando.riptide.spring.AccessTokensDefaultCredentialsDirectoryTest#shouldUseCredentialsDirectory -DnondexRuns=10  || echo "NonDex failed" > nondex_result.txt
-        working-directory: ${{ github.workspace }}/riptide
-        continue-on-error: true
-      - name: Check NonDex results
-        if: steps.nondex.outcome == 'failure'
-        run: echo "has flaky"
+#       # - name: Run the test
+#       #   run: mvn -pl mockserver-core test -Dtest=org.mockserver.serialization.serializers.body.JsonBodySerializerTest#shouldSerializeJsonBodyAsObject
+#       #   working-directory: ${{ github.workspace }}/mockserver
+#       - name: Set up JDK 8 for NonDex
+#         uses: actions/setup-java@v2
+#         with:
+#           distribution: 'adopt'
+#           java-version: '8'
+#       - name: Run NonDex tool to report flaky tests
+#         id: nondex
+#         run: mvn -pl riptide-spring-boot-starter edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=org.zalando.riptide.spring.AccessTokensDefaultCredentialsDirectoryTest#shouldUseCredentialsDirectory -DnondexRuns=10  || echo "NonDex failed" > nondex_result.txt
+#         working-directory: ${{ github.workspace }}/riptide
+#         continue-on-error: true
+#       - name: Check NonDex results
+#         if: steps.nondex.outcome == 'failure'
+#         run: echo "has flaky"
 
