Update flaky-test.yml

diff --git a/.github/workflows/flaky-test.yml b/.github/workflows/flaky-test.yml
--- a/.github/workflows/flaky-test.yml
+++ b/.github/workflows/flaky-test.yml
@@ -12,21 +12,21 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
-      - name: Set up JDK 11
-        uses: actions/setup-java@v2
-        with:
-          distribution: 'adopt'
-          java-version: '11'
-      - name: Clone the typescript-generator repository
-        run: git clone https://github.com/apache/hadoop
-        working-directory: ${{ github.workspace }}
-      - name: Compile the module and dependencies (with tests)
-        run: mvn package -DskipTests  
-        working-directory: ${{ github.workspace }}/hadoop
+      # - name: Set up JDK 11
+      #   uses: actions/setup-java@v2
+      #   with:
+      #     distribution: 'adopt'
+      #     java-version: '11'
+      # - name: Clone the typescript-generator repository
+      #   run: git clone https://github.com/apache/hadoop
+      #   working-directory: ${{ github.workspace }}
+      # - name: Compile the module and dependencies (with tests)
+      #   run: mvn package -DskipTests  
+      #   working-directory: ${{ github.workspace }}/hadoop
 
-      - name: Run the test
-        run: mvn -pl hadoop-tools/hadoop-distcp test -Dtest=org.apache.hadoop.tools.util.TestThrottledInputStream#testRead
-        working-directory: ${{ github.workspace }}/hadoop
+      # - name: Run the test
+      #   run: mvn -pl hadoop-tools/hadoop-distcp test -Dtest=org.apache.hadoop.tools.util.TestThrottledInputStream#testRead
+      #   working-directory: ${{ github.workspace }}/hadoop
       - name: Set up JDK 8 for NonDex
         uses: actions/setup-java@v2
         with:
@@ -34,15 +34,10 @@ jobs:
           java-version: '8'
       - name: Run NonDex tool to report flaky tests
         id: nondex
-        run: mvn -pl hadoop-tools/hadoop-distcp edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=org.apache.hadoop.tools.util.TestThrottledInputStream#testRead -DnondexRuns=10  || echo "NonDex failed" > nondex_result.txt
+        run: mvn -pl mockserver-core edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=org.mockserver.serialization.serializers.body.JsonBodySerializerTest#shouldSerializeJsonBodyAsObject -DnondexRuns=10  || echo "NonDex failed" > nondex_result.txt
         working-directory: ${{ github.workspace }}/hadoop
         continue-on-error: true
       - name: Check NonDex results
         if: steps.nondex.outcome == 'failure'
-        run: echo "has flaky"
-
-        
-      - name: Check NonDex results      
-        if: steps.nondex.outcome == 'failure'      
         run: echo "has flaky"
 
